AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: nodejs20.x
    Timeout: 10

Resources:
  Api:
    Type: AWS::Serverless::HttpApi

  AppFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app/lambda.handler
      CodeUri: .
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref Api
            Path: /{proxy+}
            Method: ANY
      Environment:
        Variables:
          DATABASE_URL: "postgresql://user:pass@host:5432/db"